// Regenerates src/js/jumbotron-data.js: node scripts/jumbotron-data.mjs <path-or-url-to-stats.json>.
// Build/refresh time only - the page's first paint comes from this bake; oogatron-live.js
// refreshes the board at runtime.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = process.argv[2];
if (!source) {
  console.error("usage: node scripts/jumbotron-data.mjs <path-or-url-to-stats.json>");
  process.exit(2);
}

const text = /^https?:/.test(source)
  ? await (await fetch(source)).text()
  : readFileSync(source, "utf8");
const stats = JSON.parse(text);
// Only an org-wide v3 snapshot (the worker's /v2/stats) carries what this bake
// needs. While the worker still answers with an older shape, keep the
// committed bake instead of failing the deploy: the page paints from that
// file and oogatron-live.js refreshes the board at runtime.
if (stats?.meta?.schema_version !== 3 || typeof stats.meta.org !== "string" || !Array.isArray(stats.repos) || !Array.isArray(stats.recent)) {
  console.warn(`keeping the committed bake: expected an org-wide v3 snapshot, got schema_version ${stats?.meta?.schema_version}`);
  process.exit(0);
}

// Ship public handles and activity only, never profile names or metadata.
const counts = ({ commits, prs, reviews, comments }) => ({ commits, prs, reviews, comments });
const weekly = (rows) => rows.map(({ week, commits, prs, reviews, comments }) => ({ week, commits, prs, reviews, comments }));
const boards = (lb) => Object.fromEntries(["commits", "prs", "reviews", "comments"].map((kind) => [kind,
  lb[kind].map(({ login, count }) => ({ login, count }))
]));
const snapshot = {
  meta: { generated_at: stats.meta.generated_at, org: stats.meta.org, schema_version: stats.meta.schema_version },
  totals: { contributors: stats.totals.contributors, ...counts(stats.totals) },
  leaderboards: boards(stats.leaderboards),
  repos: stats.repos.map((r) => ({
    name: r.name,
    totals: { contributors: r.totals.contributors, ...counts(r.totals) },
    weekly: weekly(r.weekly),
    last_activity_at: r.last_activity_at,
    leaderboards: boards(r.leaderboards)
  })),
  recent: stats.recent.map(({ login, repo, type, occurred_at }) => ({ login, repo, type, occurred_at })),
  // The jumbotron needs logins for leaderboard labels; the caveman roster
  // needs last_seen_at for sleep states. Nothing else ships.
  contributors: stats.contributors.map((c) => ({
    login: c.login,
    last_seen_at: c.last_seen_at
  }))
};

const out = join(root, "src", "js", "jumbotron-data.js");
writeFileSync(
  out,
  `// Generated by scripts/jumbotron-data.mjs from an oogatron /v2/stats snapshot.
// Do not edit by hand.
(() => {
  "use strict";
  const BL = window.BL = window.BL || {};
  BL.jumbotronData = ${JSON.stringify(snapshot)};
})();
`,
);
console.log(`wrote ${out} (${stats.repos.length} repos, ${stats.contributors.length} contributors, generated_at ${stats.meta.generated_at})`);
