// Regenerates src/js/jumbotron-data.js from an oogatron stats snapshot.
// Usage: node scripts/jumbotron-data.mjs <path-or-url-to-stats.json>
// The page stays network-free: this runs at build/refresh time only.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = process.argv[2];
if (!source) {
  console.error("usage: node scripts/jumbotron-data.mjs <path-or-url-to-stats.json>");
  process.exit(2);
}

const text = /^https?:/.test(source)
  ? await (await fetch(source)).text()
  : readFileSync(source, "utf8");
const stats = JSON.parse(text);
if (stats?.meta?.schema_version !== 1) {
  console.error(`unexpected schema_version: ${stats?.meta?.schema_version}`);
  process.exit(1);
}

const out = join(root, "src", "js", "jumbotron-data.js");
writeFileSync(
  out,
  `// Generated by scripts/jumbotron-data.mjs from an oogatron /v1/stats snapshot.
// Do not edit by hand.
(() => {
  "use strict";
  const BL = window.BL = window.BL || {};
  BL.jumbotronData = ${JSON.stringify(stats)};
})();
`,
);
console.log(`wrote ${out} (${stats.contributors.length} contributors, generated_at ${stats.meta.generated_at})`);
